# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-sulka-raspberrypi"
BBFILE_PATTERN_meta-sulka-raspberrypi = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-sulka-raspberrypi = "15"

LAYERSERIES_COMPAT_meta-sulka-raspberrypi = "wrynose"

BBFILES_DYNAMIC += " \
    meta-rugix-core:${LAYERDIR}/dynamic-layers/meta-rugix/*/*/*.bb \
    meta-rugix-core:${LAYERDIR}/dynamic-layers/meta-rugix/*/*/*.bbappend \
"
